version: "3.8"
services:
  telegram:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: telegram-bot
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
networks: {}
